version: '3.1'
services:
  db:
    image: postgres
    restart: always
    tty: true
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mmorpg
  frontend:
    tty: true
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
